# Generated by Django 2.0.5 on 2018-07-01 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='create_time',
        ),
        migrations.AddField(
            model_name='host',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(default='{}', max_length=512),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='host',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
