# Generated by Django 2.0.5 on 2018-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
