# Generated by Django 2.0.5 on 2018-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_anlyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(default='', max_length=255)),
                ('URL', models.CharField(default='', max_length=512)),
                ('STATUS', models.CharField(default='', max_length=32)),
                ('TIME', models.DateTimeField()),
            ],
        ),
    ]
